<style type="text/css">
	#footer{width: 100%;margin:50px 0px 30px 0px;text-align: center;color: #999;}
	#footer a{text-decoration: none;color: #999;}
	#footer span{color: #ddd;margin: 0 10px;}
</style>
<div id="footer">
    <a href="/" rel="nofollow">首页</a><span>|</span>
    <a href="#" rel="nofollow">帮助</a><span>|</span>
    <a href="#" rel="nofollow">关于</a>

	<p style="margin: 10px 0 0;">
		© 2015 公司 
		<a href="#" rel="nofollow">隐私政策</a> 
		<a href="#" rel="nofollow">服务条款</a> 京ICP证080268号 <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1255166386'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s95.cnzz.com/z_stat.php%3Fid%3D1255166386%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
	</p>
</div>