<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="format-detection" content="telephone=no">
	<meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0" name="viewport" />
	<meta name="Description" content="我要给差评" />
	<meta name="keywords" content="我要给差评" />
	<link rel="shortcut icon" href="/images/icon.png" type="image/x-icon">
	<link rel="stylesheet" href="/css/public.css">
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/public.js"></script>
	<title>我要给差评</title>